version: '3.7'

services:
  database:
    image: postgres
    container_name: auth_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=auth_db
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=auth
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
